# Generated by Django 5.1.7 on 2025-03-19 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('assigned_hospital', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('patient_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('date_of_birth', models.DateField()),
                ('national_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataExchange.doctorprofile')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataExchange.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataExchange.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DataExchangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='DataExchange.hospital')),
                ('sender_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='DataExchange.hospital')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataExchange.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Doctor', 'Doctor'), ('Patient', 'Patient'), ('Admin', 'Admin')], max_length=10)),
                ('contact_info', models.CharField(max_length=50, null=True, unique=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DataExchange.userprofile'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DataExchange.userprofile'),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataExchange.hospital')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DataExchange.userprofile')),
            ],
        ),
    ]
